### PR TITLE
Add script that checks generated source files

### PR DESCRIPTION
**Pull request by geigerzaehler**
Add script that typechecks generated source files.

TODO
- [x] ~~Setup CI?~~ Tracked by #17

### CODE REVIEW

**Comment by f-f** [comment]
@geigerzaehler I opened #17 to setup the CI, so this is good to go as it is.

Nice that you found that some files we have don't typecheck 😄
Did you investigate the problems any further?

**Comment by geigerzaehler** [comment]
> Did you investigate the problems any further?

I think all of them produce errors because we are trying to use `$ref` as a field name. This does not work because the `$` characters is not allowed.

**Comment by f-f** [comment]
> I think all of them produce errors because we are trying to use $ref as a field name. This does not work because the $ characters is not allowed.

Yep, tracking this in #19 now.

@geigerzaehler you should have write access now, so you can merge yourself :)

**Comment by geigerzaehler** [comment]
> @geigerzaehler you should have write access now, so you can merge yourself :)

Thanks! Could you approve the PR so I can merge?

**Review by f-f — APPROVED** [review]
Oh right sorry 👍

**Pull request merged**
