### PR TITLE
Pass natural/integer preference args to openapi-to-dhall

### PR DESCRIPTION
**Pull request by arobertn**
This PR addresses #177 by passing the `--preferNaturalInt` argument to `openapi-to-dhall` (under PR https://github.com/dhall-lang/dhall-haskell/pull/2316) and including a list of exceptions that should actually be rendered as Dhall Integer.

The list is set based on the version in `nix/nixpkgs.nix.make-dhall-kubernetes()`, determined by going through the fields in the kubernetes openapi spec files manually. It turns out that there have been no major additions / removals of such fields that should be Integers within current range of versions 1.12 - 1.22, so the list is the same for all. (If a new Kubernetes version is added and a new entry is not added here, an empty argument will be passed to `dhall-openapi` which will trigger a build failure.)

The preferred solution in #177 that the Kubernetes project includes integer ranges in their Swagger specs is in-process (https://github.com/kubernetes/kubernetes/issues/105533), but this will solve the issue in the meantime, and is isolated and easily reverted when that comes.

### CODE REVIEW

**Comment by arobertn** [comment]
I've now completed the implementation to utilize the functionality now upstream in `dhall-haskell/dhall-openapi` and checked that the list of exceptions is in fact the same for all current supported kubernetes versions.

**Comment by Gabriella439** [comment]
@arobertn: Thank you for doing this!

**Comment by arobertn** [comment]
Always good to learn something by doing. Any ideas when the next release will happen?

**Comment by uthark** [comment]
Generated Kubernetes manifests looks wrong.


`terminationGracePeriodSeconds` is `uint64` in [upstream](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2217), but generated manifests looks like this:

```
"terminationGracePeriodSeconds":30.0
```

Same issue with other fields
```
{"downwardAPI":{"defaultMode":420.0 ...
```

Default mode should be integer, not a float value.

**Comment by Gabriella439** [comment]
@uthark: Are you using `dhall-to-json` to generate the manifests?  This seems more likely to be an issue with the Dhall to JSON conversion logic than `dhall-kubernetes`, because currently the generated types specify `Natural`, which is correct: https://github.com/dhall-lang/dhall-kubernetes/search?q=terminationGracePeriodSeconds

**Pull request merged**
