### PR TITLE
Update docs/README.md.dhall to match README.md

### PR DESCRIPTION
**Pull request by WillSewell**
In a63120cd219f5421461bd92806c7e72ebc118834 and
3fdb6ca551f53d34d2e55916576faf8baa215e8a README.md had been
updated directly, without updating the "source"
docs/README.md.dhall. This commit rectifies that.

### CODE REVIEW

**Review by TristanCacqueray — APPROVED** [review]
The change seems consistent with the top-level readme.

**Comment by Gabriella439** [comment]
@WillSewell: If you merge `master` into this branch then it should pick up the changes to `./nix/kubernetes/*.txt`, which will fix the CI failure

**Comment by WillSewell** [comment]
The build step `Build of /nix/store/4i194kyg3hx3mk896ahbhnpvymxa65w5-test-dhall-kubernetes-1.17` is failing, but unfortunately there is no stdout/err visible in the hydra UI. I'm going to try and reproduce locally...

**Comment by Gabriella439** [comment]
@WillSewell: It's basically due to the same issue as before.  Fortunately, I root-caused the issue and documented what I learned here:

https://github.com/NixOS/nixpkgs/issues/109481

… and I'll have a fix for this ready soon.

**Comment by WillSewell** [comment]
Great investigation!

**Comment by Gabriella439** [comment]
@WillSewell: Alright, now the log of the failure is showing up correctly and I believe you need to run `./scripts/generate.sh 1.17` to reflect the changes you just made.

**Pull request merged**
