### PR TITLE
Set Cron* types and defaults to v1beta1

### PR DESCRIPTION
**Pull request by JamesGuthrie**
According to the Kubernetes documentation [1]:

Note: CronJob resource in batch/v2alpha1 API group has been deprecated
starting from cluster version 1.8. You should switch to using
batch/v1beta1, instead, which is enabled by default in the API server.
Examples in this document use batch/v1beta1 in all examples.

[1]: https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

This should fix the problem reported in #81

### CODE REVIEW

**Review by Gabriella439 — APPROVED** [review]
I'll merge this tomorrow unless anybody objects

**Comment by JamesGuthrie** [comment]
Actually after having looked at something linked by @f-f in #81 it looks like it would also be necessary to modify `dhall-kubernetes-generator/src/Dhall/Kubernetes/Data.hs` in order to exclude the `v2alpha1` versions instead of `v1beta1`, otherwise these changes will be overridden on the next generation.

**Comment by JamesGuthrie** [comment]
@Gabriel439 I've updated `dhall-kubernetes-generator/src/Dhall/Kubernetes/Data.hs`, but it seems to have had an impact on the actual contents of the defaults.dhall file, which may result in this breaking backwards-incompatibility. I don't know if this is a problem for dhall-kubernetes.

**Comment by Gabriella439** [comment]
@JamesGuthrie: I don't think that is an issue.  We should expect this to change the hash since the contents of the resource include the `apiVersion`

I'll merge this tomorrow if nobody objects

**Pull request merged**
