### PR TITLE
Update to Kubernetes `1.14.3`

### PR DESCRIPTION
**Pull request by f-f**
This upgrades to the latest version of `nixpkgs-channels`, which means that we get a newer version of the Kubernetes spec. It also includes some fixes to the nix workflow, that we figured it was slightly off in #70 

@arianvp do you know how to get which Kubernetes version we get for a given commit of `nixpkgs-channels`?

### CODE REVIEW

**Comment by f-f** [comment]
I am not sure why the diff says +100k lines, but the diff doesn't display them anywhere 🤔

**Comment by arianvp** [comment]
`pkgs.kubernetes.version`

**Comment by f-f** [comment]
@arianvp thanks!

We're on `1.14.3`, I'll update the title

**Comment by arianvp** [comment]
I guess we could add extracting the kube version as a build step for releases?

**Comment by f-f** [comment]
@arianvp yes! It'd be lovely to automatically have it in the README (as we are templating the README already anyways..)

**Comment by arianvp** [comment]
LGTM. we can do that hackery later

**Pull request merged**
