### PR TITLE
Prefer "schema" syntax for examples

### PR DESCRIPTION
**Pull request by gregziegan**
Our `dhall-kubernetes` usage has preferred the `Schema::{}` syntax. Aligning the public documentation with schema usage would be great for on-boarding!

(Just realized the auto-formatter defaulted to unicode characters, would maintainers rather keep ascii?)

### CODE REVIEW

**Comment by gregziegan** [comment]
hmm not sure why the hydra check is hanging. I also tried running `./scripts/generate.sh` but the nix build failed with

```
Setup: Encountered missing dependencies:
QuickCheck >=2.7 && <2.13
```

**Comment by Gabriella439** [comment]
@thebritican: I just pushed some changes which should fix the CI failures and upgrade `dhall` to version 1.27.0

**Comment by ari-becker** [comment]
Can we get a new release cut for `dhall-kubernetes` now that the `Schema::{}` syntax is the recommended means of using the repo?

**Comment by Gabriella439** [comment]
@ari-becker: I'm not sure what the release process is for `dhall-kubernetes` is.  Is it just a matter of creating a tag and a GitHub release?

**Comment by ari-becker** [comment]
@Gabriel439 yup, pretty sure that's it. Internally we're pinning to specific commits by importing `https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/7af2ab5345fbd09e02437b3a6ce8f10d9e941f4c/schemas.dhall` but obviously that's not as semantically meaningful as pinning to a version.

Ping @f-f who released 1.0.0

Related to #57

**Comment by Gabriella439** [comment]
@ari-becker: Alright, I just created a release: https://github.com/dhall-lang/dhall-kubernetes/releases/tag/v2.0.0

**Comment by f-f** [comment]
Sorry for delay; yes, a release is just a matter of creating a GitHub release here.

Thanks @Gabriel439 🙂

**Comment by Gabriella439** [comment]
@f-f: You're welcome! 🙂

**Pull request merged**
