### PR TITLE
Go back to using `--omitNull` instead of `--omitEmpty`

### LINKED ISSUE #86: Go back to --omitNull instead of --omitEmpty
... which would imply wrapping all of the non-required fields in `Optional`.

I'll admit that I originally proposed `--omitEmpty` as part of #46 but in retrospect I think it may have been a mistake, for a few reasons:

One example is the issue described in https://github.com/dhall-lang/dhall-kubernetes/issues/78 caused by using `--omitEmpty`.  There @ari-becker quoted this from the documentation:

> A label selector is a label query over a set of resources. … An empty label selector matches all objects. A null label selector matches no objects.

... but when you use `omitEmpty` there is no way to distinguish a present but empty field (which means to match everything) from an absent field (which means to match nothing).  They are semantically distinct!

Similarly, #77 was caused by the same problem: accidentally omitting a field that was a record where transitive fields were all empty (the default `EmptyDirVolumeSource`), and that was semantically not the same thing.

Also, more generally, Kubernetes is not the only configuration format that has issues like these.  For example, I ran into a similar issue when working on encoding the Mergify configuration format in Dhall as part of [this chapter](https://github.com/Gabriel439/dhall-manual/blob/54715ffe5858116dd59c8f4727f292279a4442df/manuscript/01-YamlToDhall.md) of the `dhall-manual`.  It has a `delete_head_branch` field that stores a value of type `{}` and with `--omitEmpty` there is no way to preserve that field.

The reason I'm bringing up non-Kubernetes examples is because I'm trying to slowly come up with best practices as part of writing the Dhall manual and it's becoming increasingly clear to me that `--omitEmpty` is an anti-pattern that leads to issues like these because it runs the risk of throwing away semantically significant information.

You also don't gain much these days since all that `--omitEmpty` buys you is omitting a few `Some`s.  Now that we have the `::` operator (which has higher precedence than `Some`) it's actually not that bad to just keep all the `Some`s for non-required fields.  Also if the `Some`s were to really become problematic we could always revisit that in this issue:

* [Optional record fields again](https://github.com/dhall-lang/dhall-lang/issues/778)

### PR DESCRIPTION
**Pull request by Gabriella439**
Fixes https://github.com/dhall-lang/dhall-kubernetes/issues/86

The motivation of this is to more accurately model the Kubernetes
API semantics by not auto-omitting empty fields.  This is because
a field set to `Some ([] : List T)` is not necessarily the same
as `None (List T)`.

This makes the typical case a bit more verbose (more `Some`s), but
the difference to the `./examples` shows that it's not too bad.

### CODE REVIEW

**Comment by arianvp** [comment]
Lgtm

**Review by amarrella — APPROVED** [review]
LGTM, thanks for this!

**Review by arianvp — APPROVED** [review]

**Comment by PierreR** [comment]
The script that builds the example in dhall-kubernetes still uses `--omitEmpty`
https://github.com/dhall-lang/dhall-kubernetes/blob/master/scripts/build-examples.py#L49

@Gabriel439 Is it still correct or is it something that should be changed ?

**Comment by Gabriella439** [comment]
@PierreR: That script is dead code and is not used.  I just forgot to delete it when I replaced that logic with Nix.  I have a pull request up to remove the now-defunct scripts:

https://github.com/dhall-lang/dhall-kubernetes/pull/118

**Comment by PierreR** [comment]
@Gabriel439 Thx

Looks like the nix script also uses the `--omit-empty` flag: https://github.com/dhall-lang/dhall-kubernetes/blob/master/nix/nixpkgs.nix#L80 ?

As an aside question, what's the best option for dhall-kubernetes between dhall-yaml and `dhall-json}/bin/dhall-to-yaml` ?

**Comment by Gabriella439** [comment]
@PierreR: I think both should be fine if all you use is the command-line tool.  The main advantage of the `dhall-yaml` package is that it is based on a pure Haskell implementation of YAML instead of binding to a C library for YAML support, but it is a GPL-licensed.  Functionally, they both should behave the same as far as the command-line interface goes.

I also have another pull request up to also remove the `--omit-empty` from the Nix code,
too: https://github.com/dhall-lang/dhall-kubernetes/pull/119

**Pull request merged**
